08/23/2023 12:50:39 - WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 1, distributed training: False, 16-bits training: False
Some weights of the model checkpoint at microsoft/codebert-base were not used when initializing RobertaForSequenceClassification: ['pooler.dense.bias', 'pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at microsoft/codebert-base and are newly initialized: ['classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
08/23/2023 12:50:40 - INFO - __main__ -   Training/evaluation parameters Namespace(adam_epsilon=1e-08, block_size=400, cache_dir='', config_name='', device=device(type='cuda'), do_eval=True, do_lower_case=False, do_test=True, do_train=False, dropout_probability=0, early_stopping_patience=None, epoch=1, eval_all_checkpoints=False, eval_batch_size=64, eval_data_file='/home/mdrahman/projects/data/Devign/valid.jsonl', evaluate_during_training=True, fp16=False, fp16_opt_level='O1', gradient_accumulation_steps=1, learning_rate=2e-05, local_rank=-1, logging_steps=50, max_grad_norm=1.0, max_steps=-1, min_loss_delta=0.001, mlm=False, mlm_probability=0.15, model_name_or_path='microsoft/codebert-base', model_type='roberta', n_gpu=1, no_cuda=False, num_train_epochs=1.0, output_dir='/home/mdrahman/projects//Domain-Guided-Vulnerability-Detection/saved_models', overwrite_cache=False, overwrite_output_dir=False, per_gpu_eval_batch_size=64, per_gpu_train_batch_size=32, save_steps=50, save_total_limit=None, seed=123456, server_ip='', server_port='', start_epoch=0, start_step=0, test_data_file='/home/mdrahman/projects/data/Devign/test.jsonl', tokenizer_name='microsoft/codebert-base', train_batch_size=32, train_data_file='/home/mdrahman/projects/data/Devign/train.jsonl', warmup_steps=0, weight_decay=0.0)
1
Traceback (most recent call last):
  File "run.py", line 664, in <module>
    main()
  File "run.py", line 646, in main
    model.load_state_dict(torch.load(output_dir))      
  File "/home/mdrahman/miniconda3/envs/ml/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/mdrahman/miniconda3/envs/ml/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/mdrahman/miniconda3/envs/ml/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/mdrahman/projects//Domain-Guided-Vulnerability-Detection/saved_models/checkpoint-best-acc/model.bin'
